Threads, reacts, replies, and more
EionRobb/purple-discord pull request #389
Opened 2022-01-10 22:29 UTC by dlmarquis

This is a behemoth of a PR, and I apologize for that. Adding support for threads, reactions, and replies all relied on the same core code, so I figured I'd package it all together, and then a few smaller items I was looking at also got absorbed into this PR due to shared code. Let me know if you want me to split things up or reorganize the commits.

Much of the thread code was ripped from and/or inspired by the thread support over at [slack-libpurple](https://github.com/dylex/slack-libpurple).

Threads are shown in their parent channel's chat window, but I have stored them as full channels so that we can support breaking them out into their own entities if we want to in the future.

Attempting to reply or react within a thread should not currently work.

2022-01-13 02:51 UTC, EionRobb requested changes

2022-01-13 02:51 UTC, EionRobb commented on libdiscord.c
> +discord_snowflake_from_time(time_t timestamp)
On 32-bit Linux, `time_t` is a 32bit `int`, so *1000 would overflow.  You'd need to convert to a `guint64` first

2022-01-13 02:51 UTC, EionRobb commented on libdiscord.c
> +		return 0;
mem leak here.  Need to unref mem for `local_time`, `msg_time` and `now`

2022-01-13 02:51 UTC, EionRobb commented on libdiscord.c
> +			return 0;
memleak here, need to unref `local_time`, `msg_time` and `now`

2022-01-13 02:51 UTC, EionRobb commented on libdiscord.c
> +		format = "(%F %T)";
Does this need to be localized?

2022-01-13 02:51 UTC, EionRobb commented on libdiscord.c
> +	guint len = json_array_get_length(messages);
Need to check if `len == 0`?

2022-01-13 02:51 UTC, EionRobb commented on libdiscord.c
> +			gchar *creation_time_s = g_date_time_format(creation_time, "%F %T");
Needs to be localized?

2022-01-13 02:51 UTC, EionRobb commented on libdiscord.c
> +  time_t thread_time = discord_parse_timestring(timestamp);
Whitespace issue?

2022-01-13 02:51 UTC, EionRobb commented on libdiscord.c
> +  	msg_time = discord_parse_timestring(args[0]);
whitespace issue?

2022-01-13 02:51 UTC, EionRobb commented on libdiscord.c
> +  	time_t msg_time = discord_parse_timestring(args[0]);
whitespace issue?

2022-01-13 02:51 UTC, EionRobb commented on libdiscord.c
> +	GDateTime *msg_time = g_date_time_new_from_iso8601(verified_timestring, local_time);
`g_date_time_new_from_iso8601` is too-new for win32

2022-01-13 02:51 UTC, EionRobb commented on libdiscord.c
> +		for (int i = 0; i < json_array_get_length(threads); i++) {
compile error on windows: "error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]"

2022-01-13 02:51 UTC, EionRobb commented on libdiscord.c
> +	if (pc == NULL || id == -1) {
compile error on windows: "error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]"

(id is unsigned so can never be negative)

2022-01-13 02:51 UTC, EionRobb commented on libdiscord.c
> +	gchar *color = discord_get_thread_color(ts);
Need to `g_free` color after finishing with it

2022-01-13 02:51 UTC, EionRobb commented on libdiscord.c
> +		gchar *thread_ts = discord_get_formatted_thread_timestamp(ts);
need to `g_free` thread_ts after using it

2022-01-13 02:51 UTC, EionRobb commented on libdiscord.c
> +				discord_fetch_url(da, url, NULL, discord_thread_parent_cb, from_int(thread->id));
can `thread` be `NULL`?

2022-01-13 02:51 UTC, EionRobb commented on libdiscord.c
> +			if (!g_hash_table_contains_int64(parent->threads, thread_id)) {
Could `parent` be `NULL`?

2022-01-13 02:51 UTC, EionRobb commented on libdiscord.c
> +			g_hash_table_iter_init(&thread_iter, channel->threads);
need a null check for `channel`?

2022-01-13 02:51 UTC, EionRobb commented on libdiscord.c
> +			g_hash_table_iter_init(&thread_iter, channel->threads);
the else is the same statement as in the if, do these need to be de-dup'd?

2022-01-13 02:51 UTC, EionRobb commented on libdiscord.c
> +	g_hash_table_iter_init(&iter, channel->threads);
need null-check for `channel`?

2022-01-13 02:51 UTC, EionRobb commented on libdiscord.c
> +		gchar *thread_ts = discord_get_formatted_thread_timestamp(ts);
need to `g_free` this after using it

2022-01-13 02:51 UTC, EionRobb commented on libdiscord.c
> +		return NULL;
need to free `in_progress` and `matcher`

2022-01-18 18:12 UTC, dlmarquis commented on libdiscord.c
> +		format = "(%F %T)";
If you mean does it need to be set to a local time zone, no. Since the GDateTimes have a time zone associated with them (the local one), this is done automatically.

If you mean should the string be localized for different date formats, I haven't seen any indication that vanilla libpurple/pidgin uses formats that aren't YYYY-MM-DD. I was considering adding a couple preferences to set the date format, like in slack-libpurple, but decided to put that off until after the core got merged in. I can go back and do that now, if you'd prefer.

2022-01-18 18:52 UTC, dlmarquis commented on libdiscord.c
> +			g_hash_table_iter_init(&thread_iter, channel->threads);
Right. I was originally going to allow the user to search per-guild for threads due to how the api endpoints work, then I was planning on using the space to specify archived or private threads, and then I completely forgot about that. :facepalm: 

I'll de-dup it for now.

2022-01-18 19:08 UTC, dlmarquis commented on libdiscord.c
> +				discord_fetch_url(da, url, NULL, discord_thread_parent_cb, from_int(thread->id));
It shouldn't be, but I added a check just in case

2022-01-18 19:10 UTC, dlmarquis commented on libdiscord.c
> +		return 0;
Shouldn't have to unref msg_time here, since it's NULL

2022-01-19 21:11 UTC, EionRobb commented on libdiscord.c
> +		format = "(%F %T)";
Ah, I'm thinking of how in the Pidgin .po files, there's a translatable string for how dates should be displayed...
```
#.
#. * This string determines how some dates are displayed.  The default
#. * string "%x %X" shows the date then the time.  Translators can
#. * change this to "%X %x" if they want the time to be shown first,
#. * followed by the date.
#.
#, c-format
msgid "%x %X"
msgstr "%x %X"
```

Since this function is used for outputting display dates, should we be doing something like that?  (I really did mean this as a question rather than a passive 'lets do this'.  Very curious for opinions to this query)

2022-01-19 21:16 UTC, EionRobb commented on libdiscord.c
> +			g_hash_table_iter_init(&thread_iter, channel->threads);
No harm done :)  just checking to see if there wasn't something missed, rather than it's just leaving room for future dev

2022-01-19 22:36 UTC, dlmarquis commented on libdiscord.c
> +		format = "(%F %T)";
Right now the timestring used with the slash commands needs to conform to ISO8601 (so I don't go insane trying to account for every sensible format), and that standard (or glib's implementation thereof) doesn't allow for putting the date after the time.

I think letting users format the output as time-date is going to lead to them trying to type it in as time-date, which is invalid.

2022-01-21 17:29 UTC, dlmarquis commented on libdiscord.c
> +	GDateTime *msg_time = g_date_time_new_from_iso8601(verified_timestring, local_time);
I don't know if you saw- I ripped this function from glib into its own header, and added the necessary check in glib_compat.h. I don't have a windows machine readily available, so I can't test how well that works

2022-01-23 20:53 UTC, EionRobb requested changes
Looks great, if you could just rename that `id` then I think we've got a winner :)

2022-01-23 20:53 UTC, EionRobb commented on libdiscord.c
> +	guint64 id = to_int(json_object_get_string_member(data, "channel_id"));
There's an `id` already being used in line 2459 and line 2474, so this one shadows them - might cause some issues?

2022-01-25 20:25 UTC, merged